spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST:168.231.68.22}:${DB_PORT:5432}/${DB_NAME:essenceqa_lms}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:Essence123##}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 20
      minimum-idle: 5
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    open-in-view: false

  mail:
    host: ${MAIL_HOST:smtp.hostinger.com}
    port: ${MAIL_PORT:587}
    username: ${MAIL_USERNAME:report@essenceqa.org}
    password: ${MAIL_PASSWORD:Essence123!!_}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          ssl:
            trust: smtp.hostinger.com

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

  redis:
    host: ${REDIS_HOST:redis}
    port: ${REDIS_PORT:6379}
    password: ${REDIS_PASSWORD:}
    timeout: 2000ms

server:
  port: ${SERVER_PORT:8080}
  servlet:
    context-path: /api

app:
  jwt:
    secret: ${JWT_SECRET:EssenceQA_LMS_2024_SuperSecure_JWT_Key_9x8y7z6w5v4u3t2s1r0q}
    expiration: ${JWT_EXPIRATION:86400000}
  
  cors:
    allowed-origins: ${CORS_ALLOWED_ORIGINS:https://learn.essenceqa.org}
    allowed-methods: GET,POST,PUT,DELETE,OPTIONS
    allowed-headers: "*"
    allow-credentials: true
  
  admin:
    email: ${ADMIN_EMAIL:admin@essenceqa.org}
    password: ${ADMIN_PASSWORD:Essence123!}
    firstName: ${ADMIN_FIRST_NAME:Admin}
    lastName: ${ADMIN_LAST_NAME:User}
  
  mail:
    from: ${MAIL_FROM:report@essenceqa.org}
    fromName: ${MAIL_FROM_NAME:Essence Quran Academy}
  
  file:
    upload-dir: ${FILE_UPLOAD_DIR:/app/uploads}
    max-size: ${MAX_FILE_SIZE:10MB}

  square:
    application-id: ${SQUARE_APPLICATION_ID:sandbox-sq0idb-6rXkuMFtiNc1QacPSJXq5A}
    location-id: ${SQUARE_LOCATION_ID:LTXCD6F0SCSVH}
    environment: ${SQUARE_ENVIRONMENT:sandbox}

logging:
  level:
    com.essenceqa.lms: INFO
    org.springframework.security: INFO
    org.hibernate.SQL: WARN
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
  file:
    name: /var/log/lms/application.log

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: when-authorized